/**
 * CPL Ver1.0 DB schema.
 * Processing and master data are kept separate.
 */
const DB_SCHEMA = Object.freeze([
  'DATE', 'RACECOURSE', 'RACE_NUMBER', 'COURSE',
  'SURFACE', 'DISTANCE', 'TRACK_CONDITION', 'FIELD_SIZE',
  'FIRST_POPULARITY', 'FIRST_ODDS', 'FIRST_CHEST', 'FIRST_HINDQUARTER', 'FIRST_GAIT', 'FIRST_BALANCE', 'FIRST_TONE', 'FIRST_ABDOMEN',
  'SECOND_POPULARITY', 'SECOND_ODDS', 'SECOND_CHEST', 'SECOND_HINDQUARTER', 'SECOND_GAIT', 'SECOND_BALANCE', 'SECOND_TONE', 'SECOND_ABDOMEN',
  'THIRD_POPULARITY', 'THIRD_ODDS', 'THIRD_CHEST', 'THIRD_HINDQUARTER', 'THIRD_GAIT', 'THIRD_BALANCE', 'THIRD_TONE', 'THIRD_ABDOMEN'
]);

function getDbSchema() {
  return DB_SCHEMA.slice();
}
