-- CPL Ver1.0+ / Course Research Room
-- Migration 0015: independent racecourse/course research database.
-- Facts, interpretation, requirements and ideal-body hypotheses are kept separate.

create table if not exists public.course_research (
  id bigint generated by default as identity primary key,
  racecourse text not null,
  surface text not null,
  distance integer not null check (distance > 0),
  course text not null,
  title text not null,
  official_course_image_url text,
  official_elevation_image_url text,
  official_source_url text,
  facts jsonb not null default '[]'::jsonb,
  flow jsonb not null default '[]'::jsonb,
  points jsonb not null default '[]'::jsonb,
  requirements jsonb not null default '[]'::jsonb,
  ideal_body_hypothesis jsonb not null default '{}'::jsonb,
  summary text,
  status text not null default '仮説',
  researched_at date not null default current_date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint course_research_unique unique (racecourse, surface, distance, course)
);

alter table public.course_research enable row level security;

drop policy if exists "course_research_authenticated_select" on public.course_research;
create policy "course_research_authenticated_select"
on public.course_research for select
to authenticated
using (true);

drop policy if exists "course_research_authenticated_insert" on public.course_research;
create policy "course_research_authenticated_insert"
on public.course_research for insert
to authenticated
with check (true);

drop policy if exists "course_research_authenticated_update" on public.course_research;
create policy "course_research_authenticated_update"
on public.course_research for update
to authenticated
using (true)
with check (true);

drop policy if exists "course_research_authenticated_delete" on public.course_research;
create policy "course_research_authenticated_delete"
on public.course_research for delete
to authenticated
using (true);

insert into public.course_research (
  racecourse, surface, distance, course, title,
  official_course_image_url, official_elevation_image_url, official_source_url,
  facts, flow, points, requirements, ideal_body_hypothesis, summary, status, researched_at
) values (
  '中山', '芝', 1800, '内回り', '中山 芝1800m（内回り）',
  'https://www.jra.go.jp/facilities/race/nakayama/course/img/pic_course_heimenzu.gif',
  'https://www.jra.go.jp/facilities/race/nakayama/course/img/pic_course_turf.gif',
  'https://www.jra.go.jp/facilities/race/nakayama/course/',
  '["スタンド前・ゴール前急坂の途中からスタート","1コーナーまで約200m","ゴール地点から2コーナー手前の最高地点まで上り基調","2コーナーからバックストレッチにかけて下り勾配","内回りの2・3コーナーは外回りよりタイト","最後の直線は310m","直線半ばに高低差2.2mの急坂","芝コース全体の高低差は5.3m"]'::jsonb,
  '["急坂途中からスタート","約200mで1コーナー","2コーナー手前まで上り","最高地点から下りへ","向正面から徐々に速度上昇","速度を持ってタイトな3〜4コーナー","310mの短い直線","最後に急坂","ゴール"]'::jsonb,
  '["前半は上りと1コーナーまでの短さでペースが上がりづらい","後半は下りを利用して速度が上がりやすい","速度が上がった状態でタイトな小回りコーナーを処理する","コーナー出口から短い直線、急坂まで勝負が連続する"]'::jsonb,
  '["速度と負荷の変化への対応","速度を保ちながらの小回り処理","運動を切り替えながら最後まで出力すること"]'::jsonb,
  '{"chest":"一定の厚み。最後の急坂を考えると華奢すぎない形を仮説とする","hindquarter":"重厚すぎず、シャープ寄り〜中間を仮説とする","balance":"前後の筋肉量が整い、力がスムーズに行き来する形を重視","tone":"保留。パンパン／普通／ゴム感の優劣は置かず、馬体データ側の答えを待つ","gait":"スムーズさと一定の歩幅。歩幅が長いほど良いとは断定しない","overall":"前後バランスが整い、一定の力強さを持ちながらも、重厚になりすぎずスムーズに動ける馬体"}'::jsonb,
  '前半と後半で要求される運動の質が変わり、後半は「速度上昇 → 小回り処理 → 急坂」が連続するコース。',
  '仮説',
  date '2026-09-14'
)
on conflict (racecourse, surface, distance, course) do update set
  title = excluded.title,
  official_course_image_url = excluded.official_course_image_url,
  official_elevation_image_url = excluded.official_elevation_image_url,
  official_source_url = excluded.official_source_url,
  facts = excluded.facts,
  flow = excluded.flow,
  points = excluded.points,
  requirements = excluded.requirements,
  ideal_body_hypothesis = excluded.ideal_body_hypothesis,
  summary = excluded.summary,
  status = excluded.status,
  researched_at = excluded.researched_at,
  updated_at = now();
