-- CPL Research Notes / hypothesis storage
-- Hypotheses are provisional research assets, not confirmed findings.

create table if not exists public.research_hypotheses (
  id bigint generated by default as identity primary key,
  title text not null,
  observation text not null,
  hypothesis text not null,
  verification text not null,
  status text not null default '未検証',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint research_hypotheses_title_unique unique (title),
  constraint research_hypotheses_status_check
    check (status in ('未検証', '検証中', '支持', '否定', '保留'))
);

create or replace function public.set_research_hypotheses_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists research_hypotheses_set_updated_at
on public.research_hypotheses;

create trigger research_hypotheses_set_updated_at
before update on public.research_hypotheses
for each row
execute function public.set_research_hypotheses_updated_at();

alter table public.research_hypotheses enable row level security;

drop policy if exists "research_hypotheses_authenticated_select"
on public.research_hypotheses;
create policy "research_hypotheses_authenticated_select"
on public.research_hypotheses for select
to authenticated
using (true);

drop policy if exists "research_hypotheses_authenticated_insert"
on public.research_hypotheses;
create policy "research_hypotheses_authenticated_insert"
on public.research_hypotheses for insert
to authenticated
with check (true);

drop policy if exists "research_hypotheses_authenticated_update"
on public.research_hypotheses;
create policy "research_hypotheses_authenticated_update"
on public.research_hypotheses for update
to authenticated
using (true)
with check (true);

drop policy if exists "research_hypotheses_authenticated_delete"
on public.research_hypotheses;
create policy "research_hypotheses_authenticated_delete"
on public.research_hypotheses for delete
to authenticated
using (true);

revoke all privileges on table public.research_hypotheses from public, anon;
revoke all privileges on sequence public.research_hypotheses_id_seq from public, anon;

grant select, insert, update, delete
on table public.research_hypotheses
to authenticated;

grant usage, select
on sequence public.research_hypotheses_id_seq
to authenticated;

insert into public.research_hypotheses (
  title,
  observation,
  hypothesis,
  verification,
  status
) values
(
  '芝・ダートで「歩幅長い」の意味が異なる可能性',
  E'現時点の観察では、\n芝では歩様が「歩幅長い」の好走馬が比較的多く見える一方、\nダートでは「歩幅長い」の馬は逆に成績が良くない傾向を感じる。',
  E'歩幅の長さが好走に与える影響は芝とダートで異なり、\n「歩幅長い」は芝では適性として機能しやすい一方、\nダートでは優位性にならない、\nまたは不利に働く可能性がある。',
  E'今後の蓄積データを芝／ダートで分離し、\n歩幅長い・普通・短い等の歩様分布と好走傾向を比較する。\n\nさらに競馬場・距離による偏りがないか確認する。\n\nパドックで観察した「歩幅長い」と、\nレース中のストライド長を同一視しないこと。\n\n原因・機序については現時点では確定せず、\n馬場の物理特性との関係は別途検証する。',
  '未検証'
),
(
  '阪神芝はCPLの主戦場にならない可能性',
  E'阪神競馬場の芝では、\n好走馬の馬体特徴が特定のタイプへ収束せず、\n複数の異なる馬体タイプが好走しているように感じる。',
  E'阪神芝は、\n馬体適性による好走馬の絞り込みが他の競馬場・条件より効きにくく、\nCPLの「適性照合型パドック」における\n主戦場にならない可能性がある。',
  E'阪神芝について、\n内回り／外回りを分離し、\nさらに距離別に好走馬の\n\n・胸前\n・トモ\n・歩様\n・前後バランス\n・ハリ\n・その他CPLで保存している馬体項目\n\nの分布を確認する。\n\n内外回り・距離別まで分けても\n好走馬体が広く分散するのか、\n\nそれとも特定条件では\n馬体特徴が収束するのかを検証する。\n\n現段階では\n「阪神芝はCPLに適さない」\nとは確定しない。\n\nデータ蓄積後に判断する。',
  '未検証'
)
on conflict (title) do nothing;
